services:
    sonata.admin.tag:
        class: Ens\JobeetBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: posts, label: "Blog" }
        arguments:
            - ~
            - Ens\JobeetBundle\Entity\Category
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [EnsJobeetAdminBundle]]