<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\PageBundle\Entity;

use Sonata\PageBundle\Entity\BasePage as BasePage;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/bundles/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class Page extends BasePage
{
    /**
     * @var integer $id
     */
    protected $id;
           
    /**
     * @var string
     */
    protected $gacode;

    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set gacode
     *
     * @param string $gacode
     * @return BasePage
     */
    public function setGacode($gacode)
    {
        $this->gacode = $gacode;

        return $this;
    }

    /**
     * Get gacode
     *
     * @return string 
     */
    public function getGacode()
    {
        return $this->gacode;
    }
}