<?php

namespace Sonata\PageBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class BlockAdminController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Sonata\PageBundle\Controller\BlockAdminController();
        return $instance;
    }
}
