<?php

namespace Sonata\NotificationBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class MessageAdminController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Sonata\NotificationBundle\Controller\MessageAdminController();
        return $instance;
    }
}
